### ISSUE TITLE
Can I start it with docker-compose?

### ISSUE THREAD

**Issue by ribtoks** [piratepx/app#4]
Hi

Thanks for developing piratepx. This looks simply awesome - exactly what I need for monitoring few pet projects in my home network. I would love to use it, but the installation steps do not look trivial to me. You already provide a `docker-compose.yml` for running Postgres. Would it be possible if you dockerize the app itself too?

**Comment by jstayton** [comment]
Hi Taras,

Thanks for the kind words!

I purposely _don't_ run the app itself in Docker, as I find the actual development experience slow and prone to complicate the use of other development tools (like debuggers and such). Admittedly, it has been a year or two since I last tried, so maybe it has vastly improved. 🤷🏻‍♂️

I also think it's pretty easy to setup if you're used to JavaScript/Node.js development. If not, I can understand how that may not be true.

I'm going to pass on Dockerizing it at this point, but I'll keep my mind open to it if any of my assumptions are wrong.

Thanks again!
